pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description: "Clone Repo?", name: "clone_repo")
        string(defaultValue: "https://github.com/lloydzedds/Jenkins.git", description: "Give the repo name to build", name: "repoLink")
        choice(name: 'environment', choices: ['Test', 'Dev', 'Prod'], description: 'Select the environment')
    }
    stages {
        stage('Git Clone') {
            steps {
                echo "Selected environment is ${params.environment}"
                sleep(10)
                script {
                    sh 'ls -al' 
                    sleep(10)
                    sh 'rm -rf *'
                    sleep(10)
                    sh 'ls -al'               
                    sh '''
                        if [ "${clone_repo}" = "true" ]; then
                            git clone ${repoLink}
                            echo "Git repo cloned successfully"
                            echo "Selected environment is ${environment}"
                        else
                            echo "Cloning of Git repo was skipped"
                        fi
                    '''
                }
            }
        }
        stage("list files in this directory"){
            steps{
                sleep(10)
                sh "ls -al"
            }
        }
        stage("Job Completed"){
            steps{
                sh "echo 'This has been completed sucesfully'" 
            }
        }
    }
}


// pipeline {
//     agent any
//     parameters {
//         booleanParam(defaultValue: false, description: "clone Repo?", name: "clone_repo" )
//         choice(name: 'environment', choices: ['Test', 'Dev', 'Prod'], description: 'Select the environment')
//     }
//     stages {
//         stage('Git Clone') {
//             steps {
//                 script {
//                     sh '''
//                         if [ $clone_repo = true ]
//                         then
//                             git clone https://github.com/lloydzedds/Jenkins.git'
//                             echo "Git repo cloned successfully"
//                             echo "Selected environment is $environment"
//                         else
//                             echo "Failed to clone Git repo"
//                             exit 1
//                         fi
//                     '''
//                 }
//             }
//         }
//     }
// }


// pipeline {
//     agent any
//     parameters {
//         choice (name: environment, choices: ["Test", "Dev", "Prod"], description: 'Select the environment')
//     }
//     stages {
//         stage('git clone'){
//             sh "git clone https://github.com/lloydzedds/Jenkins.git"
//             sh """
//                 if [ $? -eq 0 ]
//                 then
//                     echo "Git repo cloned successfully"
//                 fi
//             """
//         }
//     }
// }